name: Send BM Maintenance Log

on:
  schedule:
    - cron: '0 22 * * 4'

  workflow_dispatch:

jobs:
  send-mail:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Send Mail
        env:
          NAVER_ID: ${{ secrets.NAVER_ID }}
          NAVER_PASSWORD: ${{ secrets.NAVER_PASSWORD }}
          RECEIVER_EMAIL: ${{ secrets.RECEIVER_EMAIL }}
        run: |
          python send_mail.py
